// Code generated by protoc-gen-go. DO NOT EDIT.
// source: porm.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CanOp int32

const (
	CanOp_UNKNOWN CanOp = 0
	CanOp_SELECT  CanOp = 1
	CanOp_UPDATE  CanOp = 2
	CanOp_INSERT  CanOp = 4
)

var CanOp_name = map[int32]string{
	0: "UNKNOWN",
	1: "SELECT",
	2: "UPDATE",
	4: "INSERT",
}

var CanOp_value = map[string]int32{
	"UNKNOWN": 0,
	"SELECT":  1,
	"UPDATE":  2,
	"INSERT":  4,
}

func (x CanOp) String() string {
	return proto.EnumName(CanOp_name, int32(x))
}

func (CanOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b73b13ba71c9820, []int{0}
}

type Page struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b73b13ba71c9820, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Page) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Page) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type OrderBy struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Desc                 bool     `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b73b13ba71c9820, []int{1}
}

func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *OrderBy) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

type TestData struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Enable               bool     `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	Content              []byte   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Like                 int32    `protobuf:"varint,6,opt,name=like,proto3" json:"like,omitempty"`
	Score                float32  `protobuf:"fixed32,7,opt,name=score,proto3" json:"score,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestData) Reset()         { *m = TestData{} }
func (m *TestData) String() string { return proto.CompactTextString(m) }
func (*TestData) ProtoMessage()    {}
func (*TestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b73b13ba71c9820, []int{2}
}

func (m *TestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestData.Unmarshal(m, b)
}
func (m *TestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestData.Marshal(b, m, deterministic)
}
func (m *TestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestData.Merge(m, src)
}
func (m *TestData) XXX_Size() int {
	return xxx_messageInfo_TestData.Size(m)
}
func (m *TestData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestData.DiscardUnknown(m)
}

var xxx_messageInfo_TestData proto.InternalMessageInfo

func (m *TestData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestData) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TestData) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *TestData) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *TestData) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *TestData) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *TestData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TestData) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("porm.CanOp", CanOp_name, CanOp_value)
	proto.RegisterType((*Page)(nil), "porm.Page")
	proto.RegisterType((*OrderBy)(nil), "porm.OrderBy")
	proto.RegisterType((*TestData)(nil), "porm.TestData")
}

func init() { proto.RegisterFile("porm.proto", fileDescriptor_7b73b13ba71c9820) }

var fileDescriptor_7b73b13ba71c9820 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x3d, 0x6f, 0xf2, 0x30,
	0x14, 0x85, 0x5f, 0x87, 0x7c, 0xc0, 0xe5, 0x6d, 0x15, 0x59, 0x55, 0xe5, 0xad, 0x11, 0x53, 0xd4,
	0x01, 0x86, 0x2e, 0x5d, 0x0b, 0x64, 0xe8, 0x87, 0x02, 0x32, 0x41, 0x95, 0xba, 0x54, 0x26, 0xb9,
	0x54, 0x16, 0x49, 0x1c, 0x25, 0x66, 0xe0, 0xff, 0xf6, 0x87, 0x54, 0x76, 0xd2, 0x6e, 0xe7, 0x39,
	0x3a, 0xf7, 0x5c, 0x5f, 0x19, 0xa0, 0x51, 0x6d, 0x35, 0x6f, 0x5a, 0xa5, 0x15, 0x75, 0x8d, 0x9e,
	0xbd, 0x80, 0xbb, 0x15, 0x5f, 0x48, 0x6f, 0xc1, 0x57, 0xc7, 0x63, 0x87, 0x9a, 0x91, 0x88, 0xc4,
	0x2e, 0x1f, 0x88, 0xde, 0x80, 0x57, 0xca, 0x4a, 0x6a, 0xe6, 0x58, 0xbb, 0x07, 0xe3, 0x6a, 0xa5,
	0x45, 0xc9, 0x46, 0x11, 0x89, 0x47, 0xbc, 0x87, 0xd9, 0x02, 0x82, 0x4d, 0x5b, 0x60, 0xbb, 0xbc,
	0xd0, 0x10, 0x46, 0x27, 0xbc, 0xd8, 0xae, 0x09, 0x37, 0x92, 0x52, 0x70, 0x0b, 0xec, 0x72, 0xdb,
	0x33, 0xe6, 0x56, 0xcf, 0xbe, 0x09, 0x8c, 0x33, 0xec, 0xf4, 0x5a, 0x68, 0x41, 0xaf, 0xc1, 0x91,
	0xc5, 0xb0, 0xdd, 0x91, 0x85, 0x19, 0xa8, 0x45, 0x85, 0x76, 0x60, 0xc2, 0xad, 0x36, 0xaf, 0xec,
	0xb4, 0xd0, 0xe7, 0xce, 0x2e, 0xbe, 0xe2, 0x03, 0x19, 0x1f, 0x6b, 0x71, 0x28, 0x91, 0xb9, 0xb6,
	0x7e, 0x20, 0xca, 0x20, 0xc8, 0x55, 0xad, 0xb1, 0xd6, 0xcc, 0x8b, 0x48, 0xfc, 0x9f, 0xff, 0xa2,
	0x69, 0x2f, 0xe5, 0x09, 0x99, 0x1f, 0x91, 0xd8, 0xe3, 0x56, 0x9b, 0xab, 0xba, 0x5c, 0xb5, 0xc8,
	0x82, 0x88, 0xc4, 0x0e, 0xef, 0x81, 0xde, 0xc1, 0x34, 0x6f, 0x51, 0x68, 0xfc, 0xd4, 0xb2, 0x42,
	0x06, 0xf6, 0x62, 0xe8, 0xad, 0x4c, 0x56, 0x36, 0x70, 0x6e, 0x8a, 0xbf, 0xc0, 0xb4, 0x0f, 0xf4,
	0x96, 0x09, 0xdc, 0x3f, 0x82, 0xb7, 0x12, 0xf5, 0xa6, 0xa1, 0x53, 0x08, 0xf6, 0xe9, 0x6b, 0xba,
	0x79, 0x4f, 0xc3, 0x7f, 0x14, 0xc0, 0xdf, 0x25, 0x6f, 0xc9, 0x2a, 0x0b, 0x89, 0xd1, 0xfb, 0xed,
	0xfa, 0x29, 0x4b, 0x42, 0xc7, 0xe8, 0xe7, 0x74, 0x97, 0xf0, 0x2c, 0x74, 0x97, 0xc1, 0x87, 0x37,
	0x9f, 0x2f, 0x9a, 0xc3, 0xc1, 0xb7, 0x7f, 0xf6, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x85, 0x25,
	0x76, 0x50, 0xc1, 0x01, 0x00, 0x00,
}
